.TH FLOW 1
.SH NAME
flow \- NetFlow exporter 
.SH SYNOPSIS
.B flow
[\fB\-f\fR \fIfile\fR]
[\fB\-c\fR \fIhostname\fR[:\fIport\fR]
[\fB\-a\fR \fIactive_timeout\fR]
[\fB\-i\fR \fIinactive_timeout\fR]
[\fB\-m\fR \fIcount\fR]
.SH DESCRIPTION
.B flow
converts network data from the given pcap file (or stdin) to NetFlow 
records and sends them to a NetFlow collector.
.SH OPTIONS
.TP
.BR \-f " " \fIfile\fR
Read the input pcap from \fIfile\fR.
.br
Default is \fIstdin\fR.
.TP
.BR \-c " " \fIhostname\fR[:\fIport\fR]
The NetFlow records are sent to \fIhostname\fR:\fIport\fR.
.br
Default is 127.0.0.1:2055.
.TP
.BR \-a " " \fIactive_timeout\fR
Sets the active timeout to \fIactive_timeout\fR seconds.
If a flow is active for at least \fIactive_timeout\fR seconds, it gets exported to the collector.
.br
Default is 60.
.TP
.BR \-i " " \fIinactive_timeout\fR
Sets the inactive timeout to \fIinactive_timeout\fR seconds.
If a flow is inactive for at least \fIinactive_timer\fR seconds, it gets exported to the collector.
.br
Default is 10.
.TP
.BR \-m " " \fIcount\fR
Sets the flow-cache size to \fIcount\fR.
If the flow-cache gets full, the oldest flow is automatically exported to the collector.
.br
Default is 1024.
